name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - run: npm i
      - run: export CYPRESS_BASE_URL=${{ github.event.deployment_status.target_url }}
      - run: npm run cypress
