name: Cypress Run

on: [deployment_status]

jobs:
  cypress-run:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm i
      - name: Set up environment
        run: export CYPRESS_BASE_URL=${{ github.event.deployment_status.target_url }}
        run: export SECRET_WORDS=${{ secrets.SECRET_WORDS }}
        run: export NETWORK_NAME=${{ secrets.NETWORK_NAME }}
        run: export CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Run Cypress
        run: npm run cypress
